version: '3.2'
services:


### prometheus + sidecars
#oldver 2.25.2

  prometheus_oneoff:
    image: prom/prometheus:v2.30.3
    container_name: prometheus_oneoff
    user: root
    volumes:
      - ./prometheus:/etc/config/
      - ./data/prometheus/other:/data
    command:
      - '--config.file=/etc/config/prometheus_oneoff.yml'
      - '--storage.tsdb.path=/data'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=180d'
      - '--web.enable-lifecycle'
      - '--web.enable-admin-api'
      - '--web.listen-address=:9001'
      - "--web.external-url=http://mon.private.com:9003"
      - '--storage.tsdb.min-block-duration=5m'
      - '--storage.tsdb.max-block-duration=5m'
    restart: always
    expose:
      - 9001
    ports:
      - "9003:9001"

  prometheus_selfmon:
    image: prom/prometheus:v2.30.3
    container_name: prometheus_selfmon
    user: root
    volumes:
      - ./prometheus:/etc/config/
      - ./data/prometheus/selfmon:/data
    command:
      - '--config.file=/etc/config/prometheus_selfmon.yml'
      - '--storage.tsdb.path=/data'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=180d'
      - '--web.enable-lifecycle'
      - '--web.enable-admin-api'
      - '--web.listen-address=:9001'
      - "--web.external-url=http://mon.private.com:9004"
      - '--storage.tsdb.min-block-duration=5m'
      - '--storage.tsdb.max-block-duration=5m'
    restart: always
    expose:
      - 9001
    ports:
      - "9004:9001"

### front-end components
  grafana:
    image: "grafana/grafana"
    container_name: grafana2
    user: root
    environment:
      - GF_USERS_ALLOW_SIGN_UP=false
    restart: always
    ports:
      - "3000:3000"
    volumes:
    - './data/grafana/varlib/_data:/var/lib/grafana'
    - './data/grafana/etc:/etc/grafana'
    - './data/grafana/log:/var/log/grafana'
    environment:
      GF_RENDERING_SERVER_URL: http://grafrender2:8081/render
      GF_RENDERING_CALLBACK_URL: http://grafana2:3000/
      GF_LOG_FILTERS: rendering:debug
  #      GF_LOG_LEVEL: debug


### alert components
  alertmanager:
    image: prom/alertmanager:latest
    container_name: alertmanager
    user: root
    volumes:
      - ./prometheus:/etc/config/
      - ./data/prometheus/alertmanager:/data
    command:
      - '--config.file=/etc/config/alertmanager.yml'
      - "--web.external-url=http://mon.private.com:9093"
    restart: always
    expose:
      - 9093
    ports:
       - "9093:9093"
