global:
  resolve_timeout: 1m
# post to slack channel prometheus-alertmanager
  slack_api_url: 'https://hooks.slack.com/services/secret'
# U052UB9V7 = paul
# U0JA27BT9 = tward


route:
  receiver: slack-untagged
  group_wait: 10s
  group_interval: 30s
  repeat_interval: 15m
  group_by: [severity, type]

  routes:
    - match:
        severity: log
      receiver: log
    - match:
        severity: pagepaul
      receiver: slack-pagepaul
    - match:
        severity: pagetward
      receiver: slack-pagetward
    - match:
        severity: actionable
      receiver: slack-actionable
      repeat_interval: 2h
      mute_time_intervals: [benicetopaul]
    - match:
        severity: ignore
      receiver: blackhole
mute_time_intervals:
  - name: benicetopaul
    time_intervals:
     # Mute all day for these days.
     - weekdays: ['Saturday','Sunday','Tuesday','Wednesday','Thursday']
     # Mute in the morning, afternoon and in the evening, any day. (gaps at 9am/13 and noon/16) (times are UTC-only)
     - times:
       - start_time: '00:00'
         end_time: '13:00'
       - start_time: '14:00'
         end_time: '16:00'
       - start_time: '17:00'
         end_time: '24:00'

receivers:
- name: 'blackhole'
- name: 'slack-untagged'
  slack_configs:
  - channel: '#prometheus-alertmanager'
    send_resolved: true
    title: |-
      [{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}] {{ .CommonLabels.alertname }} for {{ .CommonLabels.job }}
      {{- if gt (len .CommonLabels) (len .GroupLabels) -}}
        {{" "}}(
        {{- with .CommonLabels.Remove .GroupLabels.Names }}
          {{- range $index, $label := .SortedPairs -}}
            {{ if $index }}, {{ end }}
            {{- $label.Name }}="{{ $label.Value -}}"
          {{- end }}
        {{- end -}}
        )
      {{- end }}
    text: >-
      {{ range .Alerts -}}
      *Priority:* 'Unspecified'

      *Alert:* {{ .Annotations.title }}{{ if .Labels.severity }} - `{{ .Labels.severity }}`{{ end }}

      *Description:* {{ .Annotations.description }}
 
      *Details:*
        {{ range .Labels.SortedPairs }} • *{{ .Name }}:* `{{ .Value }}`
        {{ end }}
      {{ end }}
- name: 'log'
  webhook_configs:
  - url: http://webhook-logger:6725
    send_resolved: true
    max_alerts: 0
    #http_config: global.http_config
- name: 'slack-actionable'
  slack_configs:
  - channel: '#ceph'
    send_resolved: true
    title: |-
      [{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}] {{ .CommonLabels.alertname }} for {{ .CommonLabels.job }}
      {{- if gt (len .CommonLabels) (len .GroupLabels) -}}
        {{" "}}(
        {{- with .CommonLabels.Remove .GroupLabels.Names }}
          {{- range $index, $label := .SortedPairs -}}
            {{ if $index }}, {{ end }}
            {{- $label.Name }}="{{ $label.Value -}}"
          {{- end }}
        {{- end -}}
        )
      {{- end }}
    text: >-
      {{ range .Alerts -}}
      *Priority:* 'Actionable, not urgent.'

      *Alert:* {{ .Annotations.title }}{{ if .Labels.severity }} - `{{ .Labels.severity }}`{{ end }}

      *Description:* {{ .Annotations.description }}
 
      *Details:*
        {{ range .Labels.SortedPairs }} • *{{ .Name }}:* `{{ .Value }}`
        {{ end }}
      {{ end }}

- name: 'slack-pagetward'
  slack_configs:
  - channel: '#devops-alerts'
    send_resolved: true
    title: |-
      [{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}] {{ .CommonLabels.alertname }} for {{ .CommonLabels.job }}
      {{- if gt (len .CommonLabels) (len .GroupLabels) -}}
        {{" "}}(
        {{- with .CommonLabels.Remove .GroupLabels.Names }}
          {{- range $index, $label := .SortedPairs -}}
            {{ if $index }}, {{ end }}
            {{- $label.Name }}="{{ $label.Value -}}"
          {{- end }}
        {{- end -}}
        )
      {{- end }}
    text: >-
      {{ range .Alerts -}}
      *Priority:* 'Actionable, urgent.'
      *Paging:* <@secret>

      *Alert:* {{ .Annotations.title }}{{ if .Labels.severity }} - `{{ .Labels.severity }}`{{ end }}

      *Description:* {{ .Annotations.description }}
 
      *Details:*
        {{ range .Labels.SortedPairs }} • *{{ .Name }}:* `{{ .Value }}`
        {{ end }}
      {{ end }}
- name: 'slack-pagepaul'
  slack_configs:
  - channel: '#ceph'
    send_resolved: true
    title: |-
      [{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}] {{ .CommonLabels.alertname }} for {{ .CommonLabels.job }}
      {{- if gt (len .CommonLabels) (len .GroupLabels) -}}
        {{" "}}(
        {{- with .CommonLabels.Remove .GroupLabels.Names }}
          {{- range $index, $label := .SortedPairs -}}
            {{ if $index }}, {{ end }}
            {{- $label.Name }}="{{ $label.Value -}}"
          {{- end }}
        {{- end -}}
        )
      {{- end }}
    text: >-
      {{ range .Alerts -}}
      *Priority:* 'Actionable, urgent.'
      *Paging:* <@secret>

      *Alert:* {{ .Annotations.title }}{{ if .Labels.severity }} - `{{ .Labels.severity }}`{{ end }}

      *Description:* {{ .Annotations.description }}
 
      *Details:*
        {{ range .Labels.SortedPairs }} • *{{ .Name }}:* `{{ .Value }}`
        {{ end }}
      {{ end }}
